### ISSUE TITLE
Poor quality in brain tissue of the generated pseudo CT 

### ISSUE THREAD

**Issue by dongdongtong** [sitiny/mr-to-pct#3]
Hi, thanks for open source this great mr2ct translation work!

Here I got one problem as shown in the title. I downloaded the repo in my local environment and ran the code using the example T1. I didn't modify anything but I observed poor quality in the brain tissue of the generated pseudo CT. In contrast, the brain skull was just aligned with the T1w.

Could you please provide any insights on this problem, or is it just enough that we have the aligned brain skull?

The attached file is the generated CT image obtained locally.
![image](https://github.com/sitiny/mr-to-pct/assets/34974032/362b890b-1981-40cc-ac7f-c28fe1d6258c)

**Comment by sitiny** [comment]
Hi dongdongtong, 

Thanks for the question and showing the issue. There shouldn't really be any usable info in the brain and the toolbox should just give you an aligned skull as we usually just apply a threshold anyway to ignore the non-skull values. Saying that, the image you are showing doesn't correspond to what I get when I used the example image I provided, although it could just be because of different intensity windows used to display the images. It may also be a version issue. I think the last working version of MONAI that I got the toolbox to work with was 1.1. Please could you try again with that version to see if it works?

**Comment by dongdongtong** [comment]
Thanks for your kind reply. I have downgraded my monai from 1.3.0 to 1.1.0 and rerun the code on the example T1 data. Using the same window [0, 100] to visualize the data, I found the generated pseudo CT has no changes, visually. So, I got your mind. I found that in the brain skull window, i.e., [100, 1500], the generated pseudo CT is just OK (may be it is enough for the ultrasound usage.)
